---
version: '2'
services:
  memory:
    image: sby
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/sby
    command: ["sby", "-f", "memory.sby"]
  signals:
    image: sby
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/sby
    command: ["sby", "-f", "signals.sby"]
  alu:
    image: sby
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/sby
    command: ["sby", "-f", "alu.sby"]
